import pandas as pd
import streamlit as st


def render_forecast(selected_station: str, forecast_df: pd.DataFrame, forecast_horizon: int) -> None:
    st.markdown("<span class='badge badge-real'>Live ST-GNN Prediction</span>", unsafe_allow_html=True)
    st.subheader(f"Deep Learning Forecast for {selected_station}")

    chart_df = forecast_df.set_index("datetime")[["pm25_forecast", "lower", "upper"]]
    # Added accent colors for the uncertainty bands
    st.line_chart(chart_df, use_container_width=True, color=["#FF4B4B", "#FFAAAA", "#FFAAAA"])
    st.caption("pm25_forecast is dynamically generated by the PyTorch Graph Neural Network.")

    horizon_metric = forecast_df.iloc[-1]
    st.metric(
        f"Predicted PM2.5 (+{forecast_horizon}h)",
        f"{horizon_metric['pm25_forecast']:.1f} µg/m³",
        f"Range {horizon_metric['lower']:.1f} to {horizon_metric['upper']:.1f}",
    )